name: RegrowthSMP
version: '1.0.0'
main: org.lushplugins.regrowthsmp.RegrowthSMP
api-version: '1.21'
softdepend:
  - Animatronics
  - ExcellentCrates
commands:
  regrowthsmp:
    usage: /regrowthsmp
  givecosmetic:
    usage: /givecosmetic
  recipes:
    usage: /recipes
  abilities:
    usage: /abilities